### ISSUE TITLE
NoMethodError when running in heroku

### ISSUE THREAD

**Issue by kimenye** [tardate/authlogic_rpx#22]
I've encountered this issue when verifying the authenticity of the token in heroku. Any ideas?
## Environment

trevors-macbook-4:chexscheduler trevor$ heroku rake gems
(in /disk1/home/slugs/179378_c676ac0_6c60/mnt)
- [I] authlogic >= 2.1.3
  - [R] activesupport 
- [I] rpx_now >= 0.6.12
  - [I] json_pure 
- [I] authlogic_rpx >= 1.1.1
  - [I] authlogic >= 2.1.3
    - [R] activesupport 
  - [I] rpx_now >= 0.6.12
    - [I] json_pure 

I = Installed
F = Frozen
R = Framework (loaded before rails starts)
# logs

trevors-macbook-4:chexscheduler trevor$ 

Processing UserSessionsController#create (for 202.44.172.65 at 2010-05-04 23:24:13) [POST]
  Parameters: {"token"=>"a77241332a855586f23e5eda25e988e919e02080", "action"=>"create", "authenticity_token"=>"R4PJnXYOH3wn2D/G8fW0WvI4b+ruYWEBeAgUWccFvBA=", "controller"=>"user_sessions"}

NoMethodError (undefined method `add_rpx_identifier' for #<User:0x2b243cc2b538>):
  /home/slugs/179378_c676ac0_6c60/mnt/.gems/gems/authlogic_rpx-1.1.1/lib/authlogic_rpx/session.rb:165:in`validate_by_rpx'
  authlogic (2.1.3) lib/authlogic/session/callbacks.rb:72:in `validate'
  authlogic (2.1.3) lib/authlogic/session/validation.rb:64:in`valid?'
  authlogic (2.1.3) lib/authlogic/session/existence.rb:65:in `save'
  app/controllers/user_sessions_controller.rb:22:in`create'
  /home/heroku_rack/lib/static_assets.rb:9:in `call'
  /home/heroku_rack/lib/last_access.rb:25:in`call'
  /home/heroku_rack/lib/date_header.rb:14:in `call'
  thin (1.0.1) lib/thin/connection.rb:80:in`pre_process'
  thin (1.0.1) lib/thin/connection.rb:78:in `catch'
  thin (1.0.1) lib/thin/connection.rb:78:in`pre_process'
  thin (1.0.1) lib/thin/connection.rb:57:in `process'
  thin (1.0.1) lib/thin/connection.rb:42:in`receive_data'
  eventmachine (0.12.6) lib/eventmachine.rb:240:in `run_machine'
  eventmachine (0.12.6) lib/eventmachine.rb:240:in`run'
  thin (1.0.1) lib/thin/backends/base.rb:57:in `start'
  thin (1.0.1) lib/thin/server.rb:150:in`start'
  thin (1.0.1) lib/thin/controllers/controller.rb:80:in `start'
  thin (1.0.1) lib/thin/runner.rb:173:in`send'
  thin (1.0.1) lib/thin/runner.rb:173:in `run_command'
  thin (1.0.1) lib/thin/runner.rb:139:in`run!'
  thin (1.0.1) bin/thin:6
  /usr/local/bin/thin:20:in `load'
  /usr/local/bin/thin:20

**Comment by kimenye** [comment]
Just tested the sample application (without any modifications) and it works. The above error I suspect has to do with changes I've made.
